/*
maestro Service API

maestro Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileSyncerSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSyncerSpec{}

// FileSyncerSpec struct for FileSyncerSpec
type FileSyncerSpec struct {
	Files []FileObject `json:"files,omitempty"`
}

// NewFileSyncerSpec instantiates a new FileSyncerSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSyncerSpec() *FileSyncerSpec {
	this := FileSyncerSpec{}
	return &this
}

// NewFileSyncerSpecWithDefaults instantiates a new FileSyncerSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSyncerSpecWithDefaults() *FileSyncerSpec {
	this := FileSyncerSpec{}
	return &this
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *FileSyncerSpec) GetFiles() []FileObject {
	if o == nil || IsNil(o.Files) {
		var ret []FileObject
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSyncerSpec) GetFilesOk() ([]FileObject, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *FileSyncerSpec) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []FileObject and assigns it to the Files field.
func (o *FileSyncerSpec) SetFiles(v []FileObject) {
	o.Files = v
}

func (o FileSyncerSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSyncerSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

type NullableFileSyncerSpec struct {
	value *FileSyncerSpec
	isSet bool
}

func (v NullableFileSyncerSpec) Get() *FileSyncerSpec {
	return v.value
}

func (v *NullableFileSyncerSpec) Set(val *FileSyncerSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSyncerSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSyncerSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSyncerSpec(val *FileSyncerSpec) *NullableFileSyncerSpec {
	return &NullableFileSyncerSpec{value: val, isSet: true}
}

func (v NullableFileSyncerSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSyncerSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
