/*
maestro Service API

maestro Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileObject{}

// FileObject struct for FileObject
type FileObject struct {
	Name        *string `json:"name,omitempty"`
	Content     *string `json:"content,omitempty"`
	Verfication *string `json:"verfication,omitempty"`
	Path        *string `json:"path,omitempty"`
	Mode        *int32  `json:"mode,omitempty"`
	Overwrite   *bool   `json:"overwrite,omitempty"`
	User        *string `json:"user,omitempty"`
	Group       *string `json:"group,omitempty"`
}

// NewFileObject instantiates a new FileObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileObject() *FileObject {
	this := FileObject{}
	return &this
}

// NewFileObjectWithDefaults instantiates a new FileObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileObjectWithDefaults() *FileObject {
	this := FileObject{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FileObject) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FileObject) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FileObject) SetName(v string) {
	o.Name = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *FileObject) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *FileObject) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *FileObject) SetContent(v string) {
	o.Content = &v
}

// GetVerfication returns the Verfication field value if set, zero value otherwise.
func (o *FileObject) GetVerfication() string {
	if o == nil || IsNil(o.Verfication) {
		var ret string
		return ret
	}
	return *o.Verfication
}

// GetVerficationOk returns a tuple with the Verfication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetVerficationOk() (*string, bool) {
	if o == nil || IsNil(o.Verfication) {
		return nil, false
	}
	return o.Verfication, true
}

// HasVerfication returns a boolean if a field has been set.
func (o *FileObject) HasVerfication() bool {
	if o != nil && !IsNil(o.Verfication) {
		return true
	}

	return false
}

// SetVerfication gets a reference to the given string and assigns it to the Verfication field.
func (o *FileObject) SetVerfication(v string) {
	o.Verfication = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *FileObject) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *FileObject) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *FileObject) SetPath(v string) {
	o.Path = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *FileObject) GetMode() int32 {
	if o == nil || IsNil(o.Mode) {
		var ret int32
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetModeOk() (*int32, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *FileObject) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given int32 and assigns it to the Mode field.
func (o *FileObject) SetMode(v int32) {
	o.Mode = &v
}

// GetOverwrite returns the Overwrite field value if set, zero value otherwise.
func (o *FileObject) GetOverwrite() bool {
	if o == nil || IsNil(o.Overwrite) {
		var ret bool
		return ret
	}
	return *o.Overwrite
}

// GetOverwriteOk returns a tuple with the Overwrite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetOverwriteOk() (*bool, bool) {
	if o == nil || IsNil(o.Overwrite) {
		return nil, false
	}
	return o.Overwrite, true
}

// HasOverwrite returns a boolean if a field has been set.
func (o *FileObject) HasOverwrite() bool {
	if o != nil && !IsNil(o.Overwrite) {
		return true
	}

	return false
}

// SetOverwrite gets a reference to the given bool and assigns it to the Overwrite field.
func (o *FileObject) SetOverwrite(v bool) {
	o.Overwrite = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *FileObject) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *FileObject) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *FileObject) SetUser(v string) {
	o.User = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *FileObject) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileObject) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *FileObject) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *FileObject) SetGroup(v string) {
	o.Group = &v
}

func (o FileObject) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Verfication) {
		toSerialize["verfication"] = o.Verfication
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.Overwrite) {
		toSerialize["overwrite"] = o.Overwrite
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableFileObject struct {
	value *FileObject
	isSet bool
}

func (v NullableFileObject) Get() *FileObject {
	return v.value
}

func (v *NullableFileObject) Set(val *FileObject) {
	v.value = val
	v.isSet = true
}

func (v NullableFileObject) IsSet() bool {
	return v.isSet
}

func (v *NullableFileObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileObject(val *FileObject) *NullableFileObject {
	return &NullableFileObject{value: val, isSet: true}
}

func (v NullableFileObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
