/*
maestro Service API

maestro Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FileSyncerPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSyncerPatchRequest{}

// FileSyncerPatchRequest struct for FileSyncerPatchRequest
type FileSyncerPatchRequest struct {
	Spec map[string]interface{} `json:"spec,omitempty"`
}

// NewFileSyncerPatchRequest instantiates a new FileSyncerPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSyncerPatchRequest() *FileSyncerPatchRequest {
	this := FileSyncerPatchRequest{}
	return &this
}

// NewFileSyncerPatchRequestWithDefaults instantiates a new FileSyncerPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSyncerPatchRequestWithDefaults() *FileSyncerPatchRequest {
	this := FileSyncerPatchRequest{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *FileSyncerPatchRequest) GetSpec() map[string]interface{} {
	if o == nil || IsNil(o.Spec) {
		var ret map[string]interface{}
		return ret
	}
	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSyncerPatchRequest) GetSpecOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Spec) {
		return map[string]interface{}{}, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *FileSyncerPatchRequest) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given map[string]interface{} and assigns it to the Spec field.
func (o *FileSyncerPatchRequest) SetSpec(v map[string]interface{}) {
	o.Spec = v
}

func (o FileSyncerPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSyncerPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableFileSyncerPatchRequest struct {
	value *FileSyncerPatchRequest
	isSet bool
}

func (v NullableFileSyncerPatchRequest) Get() *FileSyncerPatchRequest {
	return v.value
}

func (v *NullableFileSyncerPatchRequest) Set(val *FileSyncerPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSyncerPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSyncerPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSyncerPatchRequest(val *FileSyncerPatchRequest) *NullableFileSyncerPatchRequest {
	return &NullableFileSyncerPatchRequest{value: val, isSet: true}
}

func (v NullableFileSyncerPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSyncerPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
